# Generated by Django 3.2.5 on 2022-01-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('time_managing_app_back', '0002_alter_unscheduledtask_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unscheduledtask',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
